In [4]:
import pandas as pd

from config.consulta import *

In [5]:
df_funcionario, df_empresa, df_rotas = get_query()

In [7]:
df_rotas.head(10)

,id_rota,id_empresa,mes,ano,aeroporto_de_origem_sigla,aeroporto_de_origem_nome,aeroporto_de_origem_uf,aeroporto_de_origem_regiao,aeroporto_de_origem_pais,aeroporto_de_origem_continente,...,aeroporto_de_destino_continente,natureza,passageiros_pagos,passageiros_gratis,ask,rpk,distancia_voada_km,decolagens,assentos,horas_voadas
0,1,3,1,2000,SBBH,BELO HORIZONTE,MG,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,43.0,2.0,51408.0,20468.0,476.0,1.0,108.0,2.15
1,2,3,1,2000,SBBH,BELO HORIZONTE,MG,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,68.0,4.0,67200.0,23800.0,1400.0,4.0,192.0,4.14
2,468,3,2,2000,SBVT,VITORIA,ES,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,1819.0,35.0,3340660.0,760342.0,30932.0,74.0,7992.0,68.65
3,469,3,3,2000,SBBH,BELO HORIZONTE,MG,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,4692.0,134.0,7144200.0,1642200.0,66150.0,189.0,20412.0,149.13
4,470,3,3,2000,SBCT,SAO JOSE DOS PINHAIS,PR,SUL,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,77.0,0.0,77544.0,27643.0,718.0,2.0,216.0,1.88
5,471,3,3,2000,SBGL,RIO DE JANEIRO,RJ,SUDESTE,BRASIL,AMERICA DO SUL,...,EUROPA,INTERNACIONAL,47.0,0.0,1735880.0,362605.0,7715.0,1.0,225.0,9.18
6,472,3,3,2000,SBGR,GUARULHOS,SP,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,77.0,13.0,51792.0,8632.0,1079.0,13.0,624.0,7.44
7,473,3,3,2000,SBJF,JUIZ DE FORA,MG,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,42.0,0.0,17568.0,15372.0,366.0,1.0,48.0,2.37
8,474,3,3,2000,SBKP,CAMPINAS,SP,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,184.0,3.0,60756.0,16932.0,1162.0,14.0,732.0,7.85
9,10,3,1,2000,SBGL,RIO DE JANEIRO,RJ,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,112.0,6.0,41114.0,37744.0,337.0,1.0,122.0,0.95

In [30]:
df_tam = df_rotas.loc[df_rotas['id_empresa']==3]
df_tam

,id_rota,id_empresa,mes,ano,aeroporto_de_origem_sigla,aeroporto_de_origem_nome,aeroporto_de_origem_uf,aeroporto_de_origem_regiao,aeroporto_de_origem_pais,aeroporto_de_origem_continente,...,aeroporto_de_destino_continente,natureza,passageiros_pagos,passageiros_gratis,ask,rpk,distancia_voada_km,decolagens,assentos,horas_voadas
0,1,3,1,2000,SBBH,BELO HORIZONTE,MG,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,43.0,2.0,51408.0,20468.0,476.0,1.0,108.0,2.15
1,2,3,1,2000,SBBH,BELO HORIZONTE,MG,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,68.0,4.0,67200.0,23800.0,1400.0,4.0,192.0,4.14
2,468,3,2,2000,SBVT,VITORIA,ES,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,1819.0,35.0,3340660.0,760342.0,30932.0,74.0,7992.0,68.65
3,469,3,3,2000,SBBH,BELO HORIZONTE,MG,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,4692.0,134.0,7144200.0,1642200.0,66150.0,189.0,20412.0,149.13
4,470,3,3,2000,SBCT,SAO JOSE DOS PINHAIS,PR,SUL,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,77.0,0.0,77544.0,27643.0,718.0,2.0,216.0,1.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8674,14584,3,12,2004,SBSV,SALVADOR,BA,NORDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,3749.0,29.0,8515980.0,6247960.0,65340.0,45.0,5865.0,105.39
8675,14585,3,12,2004,SBVT,VITORIA,ES,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,3618.0,47.0,4802650.0,2808110.0,44469.0,61.0,6588.0,96.50
8676,14586,3,12,2004,SCEL,SANTIAGO,None,None,CHILE,AMERICA DO SUL,...,AMERICA DO SUL,INTERNACIONAL,132.0,36.0,NaN,NaN,NaN,NaN,NaN,NaN
8677,14587,3,12,2004,SCEL,SANTIAGO,None,None,CHILE,AMERICA DO SUL,...,AMERICA DO SUL,INTERNACIONAL,925.0,86.0,11825700.0,2763000.0,75806.0,29.0,4524.0,107.27
8678,14588,3,12,2004,SWKN,CALDAS NOVAS,GO,CENTRO-OESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,62.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
lista = ['mes', 'ano', 'aeroporto_de_origem_nome', 'aeroporto_de_destino_nome', 'passageiros_pagos', 'passageiros_gratis']

In [42]:
df_trafego = df_tam[lista]

In [45]:
df_teste = df_trafego.groupby(['aeroporto_de_origem_nome', 'aeroporto_de_destino_nome', 'ano']).sum().reset_index()

In [46]:
df_teste.head()

,aeroporto_de_origem_nome,aeroporto_de_destino_nome,ano,mes,passageiros_pagos,passageiros_gratis
0,ARACAJU,GUARULHOS,2002,42,531.0,66.0
1,ARACAJU,GUARULHOS,2003,21,910.0,54.0
2,ARACAJU,GUARULHOS,2004,36,1430.0,1.0
3,ARACAJU,RIO DE JANEIRO,2001,63,669.0,81.0
4,ARACAJU,RIO DE JANEIRO,2002,78,1636.0,154.0