In [1]:
import pandas as pd

from config.consulta import *

In [2]:
df_funcionario, df_empresa, df_rotas = get_query()

Conexão bem-sucedida!

c:\Users\fvito\OneDrive\Documentos\GitHub\Airlines-Dashboard---Projetos1-IFSP\config\consulta.py:27: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

Conexão bem-sucedida!

c:\Users\fvito\OneDrive\Documentos\GitHub\Airlines-Dashboard---Projetos1-IFSP\config\consulta.py:27: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

Conexão bem-sucedida!

c:\Users\fvito\OneDrive\Documentos\GitHub\Airlines-Dashboard---Projetos1-IFSP\config\consulta.py:27: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

In [6]:
df_rotas.head(10)

,id_rota,id_empresa,mes,ano,aeroporto_de_origem_sigla,aeroporto_de_origem_nome,aeroporto_de_origem_uf,aeroporto_de_origem_regiao,aeroporto_de_origem_pais,aeroporto_de_origem_continente,...,aeroporto_de_destino_continente,natureza,passageiros_pagos,passageiros_gratis,ask,rpk,distancia_voada_km,decolagens,assentos,horas_voadas
0,1,3,1,2000,SBBH,BELO HORIZONTE,MG,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,43.0,2.0,51408.0,20468.0,476.0,1.0,108.0,2.15
1,2,3,1,2000,SBBH,BELO HORIZONTE,MG,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,68.0,4.0,67200.0,23800.0,1400.0,4.0,192.0,4.14
2,468,3,2,2000,SBVT,VITORIA,ES,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,1819.0,35.0,3340660.0,760342.0,30932.0,74.0,7992.0,68.65
3,469,3,3,2000,SBBH,BELO HORIZONTE,MG,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,4692.0,134.0,7144200.0,1642200.0,66150.0,189.0,20412.0,149.13
4,470,3,3,2000,SBCT,SAO JOSE DOS PINHAIS,PR,SUL,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,77.0,0.0,77544.0,27643.0,718.0,2.0,216.0,1.88
5,471,3,3,2000,SBGL,RIO DE JANEIRO,RJ,SUDESTE,BRASIL,AMERICA DO SUL,...,EUROPA,INTERNACIONAL,47.0,0.0,1735880.0,362605.0,7715.0,1.0,225.0,9.18
6,472,3,3,2000,SBGR,GUARULHOS,SP,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,77.0,13.0,51792.0,8632.0,1079.0,13.0,624.0,7.44
7,473,3,3,2000,SBJF,JUIZ DE FORA,MG,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,42.0,0.0,17568.0,15372.0,366.0,1.0,48.0,2.37
8,474,3,3,2000,SBKP,CAMPINAS,SP,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,184.0,3.0,60756.0,16932.0,1162.0,14.0,732.0,7.85
9,10,3,1,2000,SBGL,RIO DE JANEIRO,RJ,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,112.0,6.0,41114.0,37744.0,337.0,1.0,122.0,0.95

In [7]:
df_tam = df_rotas.loc[df_rotas['id_empresa']==3]
df_tam

,id_rota,id_empresa,mes,ano,aeroporto_de_origem_sigla,aeroporto_de_origem_nome,aeroporto_de_origem_uf,aeroporto_de_origem_regiao,aeroporto_de_origem_pais,aeroporto_de_origem_continente,...,aeroporto_de_destino_continente,natureza,passageiros_pagos,passageiros_gratis,ask,rpk,distancia_voada_km,decolagens,assentos,horas_voadas
0,1,3,1,2000,SBBH,BELO HORIZONTE,MG,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,43.0,2.0,51408.0,20468.0,476.0,1.0,108.0,2.15
1,2,3,1,2000,SBBH,BELO HORIZONTE,MG,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,68.0,4.0,67200.0,23800.0,1400.0,4.0,192.0,4.14
2,468,3,2,2000,SBVT,VITORIA,ES,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,1819.0,35.0,3340660.0,760342.0,30932.0,74.0,7992.0,68.65
3,469,3,3,2000,SBBH,BELO HORIZONTE,MG,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,4692.0,134.0,7144200.0,1642200.0,66150.0,189.0,20412.0,149.13
4,470,3,3,2000,SBCT,SAO JOSE DOS PINHAIS,PR,SUL,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,77.0,0.0,77544.0,27643.0,718.0,2.0,216.0,1.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9482,47,3,1,2000,SBSR,SAO JOSE DO RIO PRETO,SP,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,79.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN
9483,48,3,1,2000,SBUL,UBERLANDIA,MG,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,113.0,2.0,116208.0,60794.0,1076.0,2.0,216.0,2.98
9484,49,3,1,2000,SBVT,VITORIA,ES,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,87.0,1.0,45036.0,36279.0,417.0,1.0,108.0,1.25
9485,50,3,1,2000,SBVT,VITORIA,ES,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,75.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
9486,51,3,1,2000,SBVT,VITORIA,ES,SUDESTE,BRASIL,AMERICA DO SUL,...,AMERICA DO SUL,DOMESTICA,2306.0,70.0,3385800.0,963908.0,31350.0,75.0,8100.0,69.52

In [ ]:
"""
'aeroporto_de_origem_nome', 
    'aeroporto_de_destino_nome', 
    'mes', 
    'ano', 
    'passageiros_pagos', 
    'passageiros_gratis',
    'ask',
    'rpk',
    'distancia_voada_km',
    'decolagens',
    'horas_voadas',
    'assentos'
"""

In [16]:
lista = [
    'aeroporto_de_origem_nome', 
    'aeroporto_de_destino_nome', 
    'mes', 
    'ano', 
    'passageiros_pagos', 
    'passageiros_gratis',
]
df_sazonal = df_tam[lista]

In [45]:

# Supondo que o DataFrame se chama df
# Criar colunas de ano e trimestre
df_sazonal['mes'] = pd.to_datetime(df_sazonal['mes'], format='%m')  # Certificar-se de que a coluna 'mes' está no formato correto
df_sazonal['trimestre'] = df_sazonal['mes'].dt.quarter

# Calcular a procura total em cada trimestre (todos os anos)
df_sazonal['passageiros_total'] = df_sazonal['passageiros_pagos'] + df_sazonal['passageiros_gratis']
trimestre_total = df_sazonal.groupby('trimestre')['passageiros_total'].sum().reset_index()


# Calcular a porcentagem de procura por trimestre
#df_trimestre = df_sazonal.merge(trimestre_total, on='trimestre', suffixes=('', '_trimestre_total'))
#df_trimestre['procura_porcentagem'] = (df_trimestre['passageiros_total'] / df_trimestre['passageiros_total_trimestre_total']) * 100


# Calcular a procura total anual
total_anual = df_sazonal['passageiros_total'].sum()

# Calcular a porcentagem de procura por trimestre
trimestre_total['procura_porcentagem'] = (trimestre_total['passageiros_total'] / total_anual) * 100


# Encontrar o trajeto mais procurado em cada trimestre (todos os anos)
trajeto_mais_procurado = df_sazonal.groupby(['trimestre', 'aeroporto_de_origem_nome', 'aeroporto_de_destino_nome'])['passageiros_total'].sum().reset_index()
trajeto_mais_procurado = trajeto_mais_procurado.sort_values(by=['trimestre', 'passageiros_total'], ascending=[True, False])
trajeto_mais_procurado = trajeto_mais_procurado.groupby('trimestre').first().reset_index()

C:\Users\fvito\AppData\Local\Temp\ipykernel_18732\4144516139.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sazonal['mes'] = pd.to_datetime(df_sazonal['mes'], format='%m')  # Certificar-se de que a coluna 'mes' está no formato correto
C:\Users\fvito\AppData\Local\Temp\ipykernel_18732\4144516139.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sazonal['trimestre'] = df_sazonal['mes'].dt.quarter
C:\Users\fvito\AppData\Local\Temp\ipykernel_18732\4144516139.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sazonal['passageiros_total'] = df_sazonal['passageiros_pagos'] + df_sazonal['passageiros_gratis']

In [52]:
# Encontrar a linha com o maior valor na coluna 'passageiros_total' 
indice_maior_valor = trimestre_total['procura_porcentagem'].idxmax()
trimestre_total['possiveis_otimizacoes'] = '' 
trimestre_total.loc[indice_maior_valor, 'possiveis_otimizacoes'] = 'Este é o semestre de maior procura durante o ano, focar em oferecer mais opções de voos e ter maior atenção na frota de aeronaves, seja aumentando a frota ou oferecendo mais manutenções'
    
# Encontrar a linha com o menor valor na coluna 'passageiros_total' 
indice_maior_valor = trimestre_total['procura_porcentagem'].idxmin()
trimestre_total['possiveis_otimizacoes'] = '' 
trimestre_total.loc[indice_maior_valor, 'possiveis_otimizacoes'] = 'Este é o semestre de menor procura durante o ano, focar em oferecer promoções durante o semestre e pensar em uma boa logistica para não usar aeronaves que serão importantes para outros momentos de maior fluxo de passageiros'

"""
if trimestre_total.loc[trimestre_total['passageiros_total'].idxmin()]:
    trimestre_total['possiveis_otimizacoes'] = ''

"""

"# Encontrar a linha com o menor valor na coluna 'passageiros_total' \nif trimestre_total.loc[trimestre_total['passageiros_total'].idxmin()]:\n    trimestre_total['possiveis_otimizacoes'] = 'Este é o semestre de menor procura durante o ano, focar em oferecer promoções durante o semestre e pensar em uma boa logistica para não usar aeronaves que serão importantes para outros momentos de maior fluxo de passageiros'\n\n"

In [53]:
trimestre_total.head()

,trimestre,passageiros_total,procura_porcentagem,possiveis_otimizacoes
0,1,3587605.0,23.255147,
1,2,3764567.0,24.402229,
2,3,4024444.0,26.086773,
3,4,4050528.0,26.255851,Este é o semestre de maior procura durante o a...

In [48]:
trajeto_mais_procurado.head()

,trimestre,aeroporto_de_origem_nome,aeroporto_de_destino_nome,passageiros_total
0,1,RIO DE JANEIRO,SAO PAULO,502684.0
1,2,SAO PAULO,RIO DE JANEIRO,636631.0
2,3,SAO PAULO,RIO DE JANEIRO,622447.0
3,4,SAO PAULO,RIO DE JANEIRO,599750.0